# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
    python: python3
repos:
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.3.0
  hooks:
  - id: add-trailing-comma
    args: [--py36-plus]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.1.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.8.5
  hooks:
  - id: reorder-python-imports
    args: [--py3-plus]
# - repo: https://github.com/asottile/setup-cfg-fmt
#   rev: v1.20.0
#   hooks:
#   - id: setup-cfg-fmt
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.35.0
  hooks:
  - id: commitizen
    stages: [commit-msg]
# - repo: https://github.com/Lucas-C/pre-commit-hooks-go
#   rev: v1.0.1
#   hooks:
#   - id: checkmake
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.7.0
  hooks:
    - id: autopep8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.982
  hooks:
  - id: mypy
    args: [--ignore-missing-imports, --install-types, --non-interactive]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-builtin-literals
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  # - id: check-symlinks
  # - id: check-toml
  - id: check-vcs-permalinks
  # - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  # - id: detect-aws-credentials
  - id: detect-private-key
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  # - id: file-contents-sorter
  - id: fix-byte-order-marker
  # - id: fix-encoding-pragma
  # - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: name-tests-test
  - id: no-commit-to-branch
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys]
  # - id: requirements-txt-fixer
  # - id: sort-simple-yaml
  - id: trailing-whitespace
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      additional_dependencies: [flake8-typing-imports==1.7.0]
